import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster"
import { FirebaseClientProvider } from '@/firebase';
import Header from '@/components/header';

export const metadata: Metadata = {
  title: 'ExoPredict',
  description: 'An exoplanet prediction tool generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <FirebaseClientProvider>
            <div className="container mx-auto min-h-screen p-4 sm:p-6 lg:p-8">
              <Header />
              {children}
            </div>
          <Toaster />
        </FirebaseClientProvider>
      </body>
    </html>
  );
}
